# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Project
group=io.github.thebluetropics
version=0.1.0-alpha

# Maven
artifact_name=example-mod

# Mod
mod_id=example_mod

# Minecraft
minecraft_version=1.21.1

# Fabric
fabric_loader_version=0.16.12
fabric_api_version=0.102.0+1.21.1

# Mappings
mappings_version=1.21.1+build.3

# Github
github_packages_url=https://maven.pkg.github.com/thebluetropics/fabric-example-mod

# Mod Menu
modmenu_version=11.0.3
