# Note: this `mod.toml` file is currently intended for my own use and can safely be removed.

[specification]
version = "0.1"

[mod]
id = "example_mod"
name = "Example Mod"
version = "0.1.0"
license = "MIT"
description = "An example Fabric mod"
summary = "An example Fabric mod"
environments.client = true
environments.server = true

[[mod.authors]]
name = "thebluetropics"
email = "thebluetropics@gmail.com"
github_profile = "https://github.com/thebluetropics"
website = "https://github.com/thebluetropics"

# [[mod.contributors]]
# name = "a contributor"

[[mod.social_links]]
name = "Discord"
link = "https://discord.com/invite/A9hgghDk48"

[mod.contact]
website = "https://github.com/thebluetropics/fabric-example-mod"
sources = "https://github.com/thebluetropics/fabric-example-mod"
issues = "https://github.com/thebluetropics/fabric-example-mod/issues"

# [mod.translated.id_ID]
# name = "Example Mod"
